### ISSUE TITLE
Changing the CompleteStudentsQueueMessageAsync method still makes ShouldListenToStudentEvent() unit test pass

### ISSUE THREAD

**Issue by jayendusharma** [hassanhabib/CulDeSacDemoApi#1]
Just wanted to understand how the Unit test can correctly check the behavior of the call-site. If we modify the QueueBroker.Students.cs as

```csharp

namespace CulDeSacApi.Brokers.Queues
{
    public partial class QueueBroker
    {
        public IQueueClient StudentsQueue { get; set; }

        public void ListenToStudentsQueue(Func<Message, CancellationToken, Task> eventHandler)
        {
            MessageHandlerOptions messageHandlerOptions = GetMessageHandlerOptions();
            this.StudentsQueue.RegisterMessageHandler(CompleteStudentsQueueMessageAsync, messageHandlerOptions);
        }

        private Task CompleteStudentsQueueMessageAsync(
            Message message , CancellationToken cancellation)
        {
            return Task.CompletedTask;
        }
    }
}
```
The Unit test ShouldListenToStudentEvent() in StudentEventServiceTests.Logic.Listen.cs still passes, but the call-site logic of CompleteStudentsQueueMessageAsync has been changed

**Comment by hassanhabib** [comment]
@jayendusharma changing the brokers isn't going to change anything for unit tests. Unit tests mock the interfaces or the contracts of the brokers. Their main focus is the service itself in isolation of all it's dependencies.
